import { Track } from './types';

export const MOCK_TRACKS: Track[] = [
  {
    id: 'eGBGWHMPMG4',
    title: 'Muộn Rồi Mà Sao Còn',
    artist: 'Sơn Tùng M-TP',
    album: 'Sky Tour',
    duration: 243,
    mood: 'suy',
    plays: 3200000,
    albumArt: 'https://i.ytimg.com/vi/eGBGWHMPMG4/maxresdefault.jpg',
    url: '',
  },
  {
    id: 'eSMVGZgMmaU',
    title: 'Chúng Ta Của Hiện Tại',
    artist: 'Sơn Tùng M-TP',
    album: 'M-TP',
    duration: 271,
    mood: 'suy',
    plays: 2800000,
    albumArt: 'https://i.ytimg.com/vi/eSMVGZgMmaU/maxresdefault.jpg',
    url: '',
  },
  {
    id: 'b5n4Q4vHRaA',
    title: 'Có Chắc Yêu Là Đây',
    artist: 'Sơn Tùng M-TP',
    album: 'Sky Tour',
    duration: 198,
    mood: 'hype',
    plays: 1900000,
    albumArt: 'https://i.ytimg.com/vi/b5n4Q4vHRaA/maxresdefault.jpg',
    url: '',
  },
  {
    id: 'T3qTEkXP1kY',
    title: 'Nơi Này Có Anh',
    artist: 'Sơn Tùng M-TP',
    album: 'M-TP',
    duration: 225,
    mood: 'overdose',
    plays: 2100000,
    albumArt: 'https://i.ytimg.com/vi/T3qTEkXP1kY/maxresdefault.jpg',
    url: '',
  },
  {
    id: 'HW0BuGBHg8E',
    title: 'Lạc Trôi',
    artist: 'Sơn Tùng M-TP',
    album: 'Sky Tour',
    duration: 259,
    mood: 'suy',
    plays: 1700000,
    albumArt: 'https://i.ytimg.com/vi/HW0BuGBHg8E/maxresdefault.jpg',
    url: '',
  },
];